---

- name: Install and configure Nextcloud on nodes within the homeassistant_instances group
  
  hosts: monitoring_instances

  vars:

    node_exporter_port: 9100
    prometheus_service_port: 9090

    # # packages: [
    # #   python-jmespath,
    # # ]

    # python_modules: [
    #   jmespath,
    # ]

    # ansible_python_interpreter: /usr/bin/python3
    # pip_package: python3-pip
    # pip_executable: pip3

    prometheus_bind_address: "{{ ansible_eth1.ipv4.address }}"

  pre_tasks:

    - name: Install dependencies
      become: yes
      import_role:
        name: greenthegarden.configure-host
        tasks_from: install-dependencies
      tags:
        - base
        - dependencies
        
  tasks:

    - name: Install node-exporter
      become: yes
      import_role:
        name: cloudalchemy.node-exporter

    - name: Install Prometheus
      become: yes
      import_role:
        name: cloudalchemy.prometheus

    # Register service from controller
    - name: Register Prometheus service with Consul
      # delegate_to: "{{ ansible_controller }}"
      consul:
        host: "{{ consul_client_address }}"
        service_name: prometheus
        service_port: "{{ prometheus_service_port }}"
        service_address: "{{ prometheus_bind_address }}"
        interval: 60s
        http: "http://{{ prometheus_bind_address }}:{{ prometheus_service_port }}/api/v1/status/runtimeinfo"
      when: service_consul_running
      