---

- name: Install and configure Nextcloud on nodes within the homeassistant_instances group
  
  hosts: monitoring_instances

  vars:

    # # packages: [
    # #   python-jmespath,
    # # ]

    # python_modules: [
    #   jmespath,
    # ]

    # ansible_python_interpreter: /usr/bin/python3
    # pip_package: python3-pip
    # pip_executable: pip3

  pre_tasks:

    - name: Install dependencies
      become: yes
      import_role:
        name: greenthegarden.configure-host
        tasks_from: install-dependencies
      tags:
        - base
        - dependencies
        
  tasks:

    - name: Install node-exporter
      become: yes
      import_role:
        name: cloudalchemy.node-exporter

    - name: Install Prometheus
      become: yes
      import_role:
        name: cloudalchemy.prometheus
