---

all:

  hosts:

    controller-node:
      ansible_host: localhost
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python
      pip_package: python-pip
      pip_executable: pip2
    homeassistant-vm:
      # ansible_host: services-node-1
      ansible_ssh_host: 172.16.1.101
      ansible_ssh_private_key_file: /home/vagrant/.ssh/id_ed25519
      ansible_ssh_user: vagrant
      consul_node_role: bootstrap
      public_iface: eth1
      # public_bind_address: "{{ ansible_ssh_host }}"

  vars:

    ansible_python_interpreter: /usr/bin/python3
    pip_package: python3-pip
    pip_executable: pip3

    # services_bind_address: "{{ ansible_ssh_host }}"

    # do not change as used to provision consul on all services_nodes
    consul_group_name: services_nodes

    service_consul_running: no

    # consul_datacenter: ha
    consul_iface: eth1
    consul_bind_address: '172.16.1.101'
    consul_recursors: ['192.168.1.254']
    consul_dnsmasq_servers: ['192.168.1.254', '8.8.8.8', '8.8.4.4']
    consul_join_wan: ['172.16.1.101']
    consul_advertise_address_wan: '172.16.1.101'
    consul_client_address: "{{ ansible_host }}"
    consul_dnsmasq_enable: yes
    consul_connect_enabled: yes
    consul_version: '1.7.1'
    # consul_install_upgrade: yes

  children:

    services_nodes:
      hosts:
        homeassistant-vm:

    monitoring_instances:
      hosts:
        homeassistant-vm:
      vars:
        prometheus_global:
          scrape_interval: 5s
          evaluation_interval: 5s

    emqx_instances:
      hosts:
        homeassistant-vm:

    tick_instances:
      hosts:
        homeassistant-vm:

    homeassistant_instances:
      hosts:
        homeassistant-vm:
